export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";

export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAIL = "STUDENT_REGISTER_FAIL";



export const EDUCATOR_LOGIN_REQUEST = "EDUCATOR_LOGIN_REQUEST";
export const EDUCATOR_LOGIN_SUCCESS = "EDUCATOR_LOGIN_SUCCESS";
export const EDUCATOR_LOGIN_FAIL = "EDUCATOR_LOGIN_FAIL";
export const EDUCATOR_LOGOUT = "EDUCATOR_LOGOUT";

export const EDUCATOR_REGISTER_REQUEST = "EDUCATOR_REGISTER_REQUEST";
export const EDUCATOR_REGISTER_SUCCESS = "EDUCATOR_REGISTER_SUCCESS";
export const EDUCATOR_REGISTER_FAIL = "EDUCATOR_REGISTER_FAIL";



export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";

export const ADD_FEEDBACK_REQUEST = "ADD_FEEDACK_REQUEST";
export const ADD_FEEDBACK_SUCCESS = "ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_FAIL = "ADD_FEEDACK_FAIL";

export const ADD_LECTURE_REQUEST = "ADD_LECTURE_REQUEST";
export const ADD_LECTURE_SUCCESS = "ADD_LECTURE_SUCCESS";
export const ADD_LECTURE_FAIL = "ADD_LECTURE_FAIL";


export const GET_LECTURE_LIST_REQUEST = "GET_LECTURE_LIST_REQUEST";
export const GET_LECTURE_LIST_SUCCESS = "GET_LECTURE_LIST_SUCCESS";
export const GET_LECTURE_LIST_FAIL = "GET_LECTURE_LIST_FAIL";

export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAIL = "GET_COURSES_FAIL";

export const REMOVE_LECTURE_REQUEST = "REMOVE_LECTURE_REQUEST";
export const REMOVE_LECTURE_SUCCESS = "REMOVE_LECTURE_SUCCESS";
export const REMOVE_LECTURE_FAIL = "REMOVE_LECTURE_FAIL";


export const EDUCATOR_REQUEST = "EDUCATOR_REQUEST";
export const EDUCATOR_SUCCESS = "EDUCATOR_SUCCESS";
export const EDUCATOR_FAIL = "EDUCATOR_FAIL";

export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAIL = "STUDENT_FAIL";

export const GET_INSTRUCTORS_FEEDBACK_REQUEST = "GET_INSTRUCTORS_FEEDBACK_REQUEST";
export const GET_INSTRUCTORS_FEEDBACK_SUCCESS = "GET_INSTRUCTORS_FEEDBACK_SUCCESS";
export const GET_INSTRUCTORS_FEEDBACK_FAIL = "GET_INSTRUCTORS_FEEDBACK_FAIL";

export const EDUCATOR_LIST_REQUEST = "EDUCATOR_LIST_REQUEST";
export const EDUCATOR_LIST_SUCCESS = "EDUCATOR_LIST_SUCCESS";
export const EDUCATOR_LIST_FAIL = "EDUCATOR_LIST_FAIL";